### ISSUE TITLE
能否做成一个简易的后台管理系统

### ISSUE THREAD

**Issue by akFace** [kuaifan/eeui-service#1]
#### 能否做成一个简易的，可一键部署的后台管理系统，或者有没有nodejs版本，对PHP不太熟悉 :joy:

**Comment by kuaifan** [comment]
后台管理系统用 https://console.eeui.app/ 就好了嘛😂

**Comment by akFace** [comment]
> 后台管理系统用 https://console.eeui.app/ 就好了嘛😂

用这个就是为了能在自己的服务器上跑，用 https://console.eeui.app 那这个开源就没什么意义了 😂

**Comment by kuaifan** [comment]
争取出个nodejs版本吧

**Comment by akFace** [comment]
> 争取出个nodejs版本吧

哈哈，可以
